# Generated by Django 4.2.7 on 2023-11-17 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_curses', models.CharField(max_length=255)),
                ('num_curses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SemestrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semester', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_teacher', models.CharField(max_length=100)),
                ('last_name_teacher', models.CharField(max_length=100)),
                ('rank_teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_student_cards', to='api_student.studentmodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_student_cards', to='api_student.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
                ('date_end', models.DateField()),
                ('id_curses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_curses', to='api_student.cursesmodel')),
                ('id_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_semester', to='api_student.studentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='cursesmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_student.studentmodel'),
        ),
    ]
