# Generated by Django 4.2.7 on 2023-11-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursesmodel',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='semestercursesmodel',
            options={'verbose_name': 'Семестр Курса', 'verbose_name_plural': 'Семестры Курсов'},
        ),
        migrations.AlterModelOptions(
            name='semestrmodel',
            options={'verbose_name': 'Семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AlterModelOptions(
            name='studentcardmodel',
            options={'verbose_name': 'Карта Студента', 'verbose_name_plural': 'Карты Студентов'},
        ),
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='semester',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='id_semester_teacher', to='api_student.semestrmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semestercursesmodel',
            name='id_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_semester', to='api_student.semestrmodel'),
        ),
    ]
