# Generated by Django 4.2.7 on 2023-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_student', '0002_alter_cursesmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursesmodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='semester',
        ),
        migrations.AddField(
            model_name='cursesmodel',
            name='student',
            field=models.ManyToManyField(to='api_student.studentmodel'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='semester',
            field=models.ManyToManyField(to='api_student.semestrmodel'),
        ),
    ]
